frontend:
  replicaCount: 2
  image:
    repository: skouzz/frontend
    tag: latest
  service:
    type: LoadBalancer
    port: 80

backend:
  replicaCount: 2
  image:
    repository: skouzz/backend
    tag: latest
  service:
    type: ClusterIP
    port: 5000

mongodb:
  enabled: true
  persistence:
    size: 1Gi