apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: skouzz/backend  # Your backend Docker image
          ports:
            - containerPort: 5000  # Exposing port 5000 inside the container
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: "256Mi"  # Amount of memory requested
              cpu: "250m"      # Amount of CPU requested
            limits:
              memory: "512Mi"  # Maximum memory the container can use
              cpu: "500m"      # Maximum CPU the container can use
      restartPolicy: Always  # Ensures that pods are restarted if they fail
