apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: skouzz/backend  # Your frontend Docker image
          ports:
            - containerPort: 5000  # Exposing port 3000 inside the container
          resources:
            requests:
              memory: "256Mi"  # Amount of memory requested
              cpu: "250m"      # Amount of CPU requested
            limits:
              memory: "512Mi"  # Maximum memory the container can use
              cpu: "500m"      # Maximum CPU the container can use
      restartPolicy: Always  # Ensures pods are always restarted if they fail
