apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: skouzz/mongo  # Your MongoDB image from Docker Hub
        ports:
        - containerPort: 27017  # MongoDB default port

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017  # MongoDB default port
      targetPort: 27017
      nodePort: 30017  # Expose MongoDB on port 30017 (can change if needed)
  type: NodePort  # Change from ClusterIP to NodePort
